#include <bits/stdc++.h>

using namespace std;

int bbs()
{
    int p = 22111, q = 26111; // two large prime numbers
    int n = p*q ;
    int s = n+1; // gcd(s,n) = 1 always true for this case
    int B = 0;

    long x = (s*s) % n;
    for(int i=0; i<8; i++)
    {
        x = (x*x) % n;
        B = B<<1 | (x & 1);
    }
    return B;
}

int main()
{
    int n; // rand number generated by bbs
    bbs();
}
